# Generated by Django 3.2.7 on 2021-09-11 07:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название организации')),
                ('info', models.CharField(max_length=200, verbose_name='Описание организации')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес организации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь внесший организацию в справочник')),
                ('redactor', models.ManyToManyField(related_name='companies_to_edit', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи с разрешением на редактирование')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО работника')),
                ('position', models.CharField(max_length=50, verbose_name='должность')),
                ('private_phone', models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='номер личного телефона')),
                ('work_phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='номер рабочего телефона')),
                ('fax', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='номер факса')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='api.company', verbose_name='Организация')),
            ],
        ),
    ]
