# Generated by Django 3.2.7 on 2021-09-02 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210903_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fax',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='номер факса'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='private_phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='номер личного телефона'),
        ),
    ]
