# Generated by Django 3.2.7 on 2021-09-13 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_worker_private_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='private_phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='номер личного телефона'),
        ),
    ]
